services:
  # DB For storing scraped products
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: emt
      POSTGRES_PASSWORD: emt
      POSTGRES_DB: chatbot_products
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "2345:5432"

  # Db for the LLM
  ollama_db:
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_USER: emt
      POSTGRES_PASSWORD: emt
      POSTGRES_DB: ollama_db
    volumes:
      - pgllm:/var/lib/postgresql/data
    ports:
      - "3456:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U emt -d ollama_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Ollama service
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  pgdata:
  pgllm:
  ollama: