create table product
(
    id                  bigint generated by default as identity
                        primary key,
    name                VARCHAR(255) NOT NULL,
    price_in_mkd        INTEGER NOT NULL,
    market              VARCHAR(255) NOT NULL
);